# Generated by Django 5.2.5 on 2025-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
